In [1]:
import numpy as np

In [43]:
X = np.random.randn(1000, 4)
bias = np.full((1000, 1), 3)
X_b = np.hstack((X, bias))
true_weights = np.array([[3],[5],[8],[-5],[-2]])

In [32]:
def sigmoid(z):
    return 1/(1+np.exp(-z))

In [33]:
def BCEloss(y_hat, y):
    return -np.mean(y * np.log(y_hat) + (1 - y) * np.log(1 - y_hat))

In [48]:
def gradient_descent(params, lr, X, y, iterations):
    m = X.shape[0]
    loss_history = np.zeros((iterations, 1))

    for i in range(iterations): 
        y_hat = sigmoid(X @ params)
        params -= lr * np.dot(X.T, y_hat - y) / m
        loss_history[i] = BCEloss(y_hat, y)

    return params, loss_history
    

In [49]:
params = np.zeros((X_b.shape[1], 1))
learning_rate = 0.01
iterations = 1000

logits = X_b @ true_weights + np.random.randn(1000, 1)*0.01
prob = sigmoid(logits)
y = (prob >= 0.5).astype(float)

In [50]:
params, loss_history = gradient_descent(params, learning_rate, X_b, y, iterations)

In [51]:
params

array([[ 0.47551833],
       [ 0.72810699],
       [ 1.30294548],
       [-0.79251092],
       [-0.44129356]])

In [53]:
# loss_history

In [55]:
import numpy as np

# Simulate logistic regression dataset
np.random.seed(42)
X = np.random.randn(1000, 4)
bias = np.full((1000, 1), 1)  # usually 1, not 3
X_b = np.hstack((X, bias))
true_weights = np.array([[3], [5], [8], [-5], [-2]])

# Logistic labels: use sigmoid to get probabilities, then threshold
logits = X_b @ true_weights
probabilities = 1 / (1 + np.exp(-logits))
y = (probabilities > 0.5).astype(float)  # binary labels (0 or 1)

# Sigmoid and BCE
def sigmoid(z):
    return 1 / (1 + np.exp(-z))

def BCEloss(y_hat, y):
    epsilon = 1e-10  # to prevent log(0)
    return -np.mean(y * np.log(y_hat + epsilon) + (1 - y) * np.log(1 - y_hat + epsilon))

# Gradient Descent
def gradient_descent(params, lr, X, y, iterations):
    m = X.shape[0]
    loss_history = np.zeros((iterations, 1))

    for i in range(iterations):
        y_hat = sigmoid(X @ params)
        params -= lr * X.T @ (y_hat - y) / m
        loss_history[i] = BCEloss(y_hat, y)

    return params, loss_history

# Initialize
initial_params = np.zeros((X_b.shape[1], 1))
params, history = gradient_descent(initial_params, 0.1, X_b, y, 100)


In [56]:
params

array([[ 0.49967458],
       [ 0.78426458],
       [ 1.34515128],
       [-0.82760255],
       [-0.36614439]])

In [59]:
prob = sigmoid(X_b @ params)
preds = (prob >= 0.5).astype(float)

In [61]:
np.hstack((preds, y))

array([[0., 0.],
       [1., 1.],
       [0., 0.],
       ...,
       [0., 0.],
       [0., 0.],
       [1., 1.]], shape=(1000, 2))

array([[ 0.49967458],
       [ 0.78426458],
       [ 1.34515128],
       [-0.82760255],
       [-0.36614439]])

In [98]:
X = np.random.rand(1000, 4)
bias = np.full((1000, 1), 3)
X_b = np.hstack((bias, X))
y = np.random.randint(0, 2, 1000)
y = y.reshape((1000, 1))

params = np.zeros((5,1))

def sigmoid(z):
    return 1/(1+np.exp(-z))

def BCELoss(y, y_hat):
    return -np.mean(y * np.log(y_hat) + (1-y) * np.log(1 - y_hat))

def gradient_descent(X, y, params, iterations, lr):
    m = len(y)
    loss_history = np.zeros((iterations, 1))

    for i in range(iterations):
        y_hat = sigmoid(X @ params)
        loss = BCEloss(y, y_hat)
        params -= lr * np.dot(X.T, y_hat - y) / m
        loss_history[i] = loss

gradient_descent(X_b, y, params, 1000, 0.01)

In [100]:
prob = sigmoid(X_b @ params)
y_hat = (prob >= 0.5).astype(float)

accuracy = np.mean(y_hat == y)
print(accuracy)

0.51
